### ISSUE TITLE
Q: how to return additional global information?

### ISSUE THREAD

**Issue by ghost** [drupal-graphql/graphql#422]
I want to communicate to the client that additional actions are needed after certain requests which the client should perform on its own and I would like to avoid creating SDK only for this purpose.

What I have in mind is for example when user calls the login method and session, token, or whatever authentication mechanism is used is returned as response, I want to tell the client to create cookie with exact name and value or when user makes api call and is authenticated with jwt and the jwt has to be rebuilt I want to let the client know to use a new token without the need to go through the login procedure by providing the token right away.

So what I have in mind is to return additional data in the response in addition to the "data" which the client can check and perform one of pre-defined actions.

Is something like this possible?

---

Or simpler example would be simply communicating `drupal_set_message()`.

---

I'm thinking a root query field would do(although another would be needed for mutations?). But am wondering how to properly collect the data(I think this module performs sub-requests) AND forcefully display(return) it.

**Comment by pmelab** [comment]
Your mutation has a return type, and there you could attach basically any data as new fields. The entity mutations for example (that have been moved to `graphql_legacy` with beta 1) return a list of errors and the created/mutated entity. The [entity mutations return type](https://github.com/drupal-graphql/graphql/blob/d01c55de16a6762e00e6c683a4af733e66eefb0d/modules/graphql_core/src/Plugin/GraphQL/Types/Mutations/EntityCrudOutput.php) is still there in the base module, to be used by custom entity mutations. Either this or your custom mutation return type is the right place. By attaching it to root you would loose the relation to the mutation that triggered the output.

A `drupal_messages` field that collects emitted messages from a query or mutation is a nice idea in general.

**Comment by ghost** [comment]
I have a FlashMessages root field that returns KeyValue(custom type) and should work in general but I am not sure it will work correctly due to the order of query processing + I think the graphql module suses subrequests so the message collection might not work correctly(I haven' had a chance to proeprly test it yet).
```

/**
 * @GraphQLField(
 *   id = "flash_messages",
 *   secure = true,
 *   name = "flashMessages",
 *   type = "KeyValue",
 *   multi = true,
 *   description = "Provides a list of flash messages. Usual types, specified by `key`, are `status`, `warning` and `error`.",
 *   weight = 1000
 * )
 */
class FlashMessages extends FieldPluginBase {

  /**
   * {@inheritdoc}
   */
  public function resolveValues($value, array $args, ResolveInfo $info) {
    foreach (drupal_get_messages() AS $type => $messages) {
      foreach ($messages AS $message) {
        yield [
          'key' => $type,
          'value' => $message
        ];
      }
    }
  }

}
```

**Comment by fubhy** [comment]
You could check out deferred resolvers (batched fields). @pmelab added that stuff and I haven't used it yet so he can probably provide more details there and whether it would cover this case too.

**Comment by pmelab** [comment]
@ivanjaros Batched fields are a application of deferred resolvers, which we implemented in the [php library itself](https://github.com/Youshido/GraphQL/blob/master/src/Execution/DeferredResolver.php). In a nutshell, it doesn't evaluate a field immediately, but first all non-deferred fields, and then the deferred ones. And if deferred resolvers return new deferred resolvers the cycle repeats until all fields are finite.

*Batched fields* are part of the Drupal module and use deferred resolving to group up compatible fields to be evaluated together. E.g. instead of fetch 5 nodes in sequence, collect 5 "requests" for nodes and fetch them all at once. Subrequests use batched fields. They first collect all information they need from a subrequest (contexts, entities, blocks ...) and evaluate all fields in one request.

So deferred resolvers are part of the solution. Making the messages a deferred field will push it safely after all other "normal" fields, but other deferred resolvers may follow. I'm not sure if there is a proper way to guarantee if a field is the "last" one, or which one is the "lastest".

**Comment by pmelab** [comment]
*Thinking out loud:* Perhaps every field (or the processor) should be able to emit messages and gather them in the query context.

**Comment by ghost** [comment]
I was thinking about this and came to a conclusion that I am looking at it from Drupal POV. By that I mean I still see backend being the decision-maker. But when it comes to decoupling frontend and backend, it should be the responsibility of the frontend to handle this exact use case and not the backend.

The backend should act as abstraction above data storage and nothing else(incl data manipulation of course). It should not force any information onto the client. The client decides what information is needed and requests it(that is the purpose of gql).

So I will most likely completely remove the field.

**Comment by fubhy** [comment]
Adding stuff to the ResolveInfo execution context is fine but I also agree with your last comment. You should probably tacke the issue from another angle entirely.
