### ISSUE TITLE
Can we make a link to d.o. GraphQL documentation

### ISSUE THREAD

**Issue by clemens-tolboom** [drupal-graphql/graphql#813]
The document links on d.o https://www.drupal.org/project/graphql

- external is not linked to the new https://drupal-graphql.gitbook.io/graphql/ #761
- please link https://www.drupal.org/project/graphql internal guide to https://www.drupal.org/docs/8/modules/graphql

Thanks

**Comment by pmelab** [comment]
Done!

**Comment by clemens-tolboom** [comment]
I still see 'No documentation guide' which should be the link to https://www.drupal.org/docs/8/modules/graphql

![drupal-graphql-link](https://user-images.githubusercontent.com/371014/67854123-101e9900-fb10-11e9-9927-2f257c100eef.png)

**Comment by pmelab** [comment]
Whoops, thanks for the headsup. Also done.

**Comment by clemens-tolboom** [comment]
The link is a little ugly **GraphQL 8.x-3.0-8.x-4.0** ... any reason for that?

I'd be happy to add a note about the version on https://www.drupal.org/docs/8/modules/graphql if needed

**Comment by pmelab** [comment]
I simplified the version constraint. But its required to add at least a minimum version.
